[project]
name = "3d-reconstruction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib==3.8.0",
    "numpy==1.26.0",
    "opencv-python==4.8.0.76",
    "scipy==1.11.2",
]
